export { default as user } from './user.png'
export { default as activityOne } from './activityOne.png'
export { default as activityTwo } from './activityTwo.png'
export { default as activityThree } from './activityThree.png'
export { default as activityFour } from './activityFour.png'